[project]
name = "permissionexample"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.9"
authors = [{ name = "Flet developer", email = "you@example.com" }]
dependencies = ["flet==0.27.6", "pyjnius", "flet-permission-handler"]

[tool.flet]
# org name in reverse domain name notation, e.g. "com.mycompany".
# Combined with project.name to build bundle ID for iOS and Android apps
org = "com.mycompany"
permissions = [
  "camera",
  "request_install_packages",
  "notification",
  "microphone",
  "access_notification_policy",
  "bluetooth",
  "bluetooth_advertise",
  "bluetooth_connect",
  "bluetooth_scan",
  "post_notifications",
  "vibrate",
  "wake_lock",
  "foreground_service",
]

# project display name that is used as an app title on Android and iOS home screens,
# shown in window titles and about app dialogs on desktop.
product = "permissionexample"

# company name to display in about app dialogs
company = "Flet"

# copyright text to display in about app dialogs
copyright = "Copyright (C) 2025 by Flet"

[tool.flet.android.permission]
"android.permission.CAMERA" = true
"android.permission.RECORD_AUDIO" = true
"android.permission.INTERNET" = true
"android.permission.ACCESS_NOTIFICATION_POLICY" = true
"android.permission.POST_NOTIFICATIONS" = true
"android.permission.VIBRATE" = true
"android.permission.WAKE_LOCK" = true
"android.permission.FOREGROUND_SERVICE" = true
"android.permission.BLUETOOTH" = true
"android.permission.BLUETOOTH_ADMIN" = true
"android.permission.BLUETOOTH_ADVERTISE" = true
"android.permission.BLUETOOTH_CONNECT" = true
"android.permission.BLUETOOTH_SCAN" = true
"android.permission.ACCESS_FINE_LOCATION" = true
"android.permission.ACCESS_COARSE_LOCATION" = true

[tool.flet.app]
path = "src"

[tool.uv]
dev-dependencies = ["flet[all]==0.27.6"]

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
flet = { extras = ["all"], version = "0.27.6" }
